export const reas = [
	{
		title: "3ème chance",
		description: "Comportementaliste animalier à Strasbourg",
		href: "https://www.3emechance.fr",
		image: "/img/troisieme-chance.webp",
		slug: "3eme-chance",
		grid: "chance",
	},
	{
		title: "Bomot",
		description: "Écrivain, auteure, biographe",
		href: "https://www.3emechance.fr",
		image: "/img/bomot.webp",
		slug: "3eme-chance",
		grid: "bomot",
	},
	{
		title: "Loïde Guitare",
		description: "Créateur de guitares originales",
		href: "https://www.3emechance.fr",
		image: "/img/loide.webp",
		slug: "3eme-chance",
		grid: "loide",
	},
	{
		title: "Hola Maté",
		description: "Boutique de maté à Strasbourg",
		href: "https://www.3emechance.fr",
		image: "/img/holamate.webp",
		slug: "3eme-chance",
		grid: "holamate",
	},
	{
		title: "Pêche exotique",
		description: "Magasin de pêche",
		href: "https://www.3emechance.fr",
		image: "/img/exotique.webp",
		slug: "3eme-chance",
		grid: "exotique",
	},
	{
		title: "Willow Tarot",
		description: "Guidance personnelle",
		href: "https://www.3emechance.fr",
		image: "/img/willow.webp",
		slug: "3eme-chance",
		grid: "willow",
	},
	{
		title: "Barber Shop",
		description: "Mockup pour un site de barbier",
		href: "https://www.3emechance.fr",
		image: "/img/barber.webp",
		slug: "3eme-chance",
		grid: "barber",
	},
	{
		title: "Fylo",
		description: "Comportementaliste animalier à Strasbourg",
		href: "https://www.3emechance.fr",
		image: "/img/fylo.webp",
		slug: "3eme-chance",
		grid: "fylo",
	},
	{
		title: "Boatman",
		description: "Distributeur de bateaux amorçeurs",
		href: "https://www.3emechance.fr",
		image: "/img/boatman.webp",
		slug: "3eme-chance",
		grid: "boatman",
	},
	{
		title: "Burgerio",
		description: "Mockup pour un restaurant de burgerss",
		href: "https://www.3emechance.fr",
		image: "/img/burgerio.webp",
		slug: "3eme-chance",
		grid: "burgerio",
	},
];
